CREATE TABLE IF NOT EXISTS `x0i_demo_profile` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `LOGIN` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255),
    `LAST_NAME` VARCHAR(255),
    `OFFSET` VARCHAR(10),

    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `x0i_demo_workday` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PROFILE_ID` INT UNSIGNED NOT NULL,
    `DATE_START` DATETIME,
    `DATE_STOP` DATETIME,

    PRIMARY KEY (`ID`),
    INDEX IX_DEMO_WORKDAY_PROFILE_ID(`PROFILE_ID`)
);

CREATE TABLE IF NOT EXISTS `x0i_demo_workday_pause` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `WORKDAY_ID` INT UNSIGNED NOT NULL,
    `DATE_START` DATETIME,
    `DATE_STOP` DATETIME,

    PRIMARY KEY (`ID`),
    INDEX IX_DEMO_WORKDAY_PAUSE_WORKDAY_ID(`WORKDAY_ID`)
);

CREATE TABLE IF NOT EXISTS `x0i_demo_lateness` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PROFILE_ID` INT UNSIGNED NOT NULL,
    `DATE` DATE,

    PRIMARY KEY (`ID`),
    INDEX IX_DEMO_LATENESS_PROFILE_ID(`PROFILE_ID`)
);